// POSTS

export const FETCHING_POSTS = "FETCHING_POSTS";
export const FETCHING_POSTS_SUCCESS = "FETCHING_POSTS_SUCCESS";
export const FETCHING_POSTS_FAIL = "FETCHING_POSTS_FAIL";

export const FETCHING_POST = "FETCHING_POST";
export const FETCHING_POST_SUCCESS = "FETCHING_POST_SUCCESS";
export const FETCHING_POST_FAIL = "FETCHING_POST_FAIL";

// AUTH

export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const UPVOTE = "UPVOTE";
export const UPVOTE_FAIL = "UPVOTE_FAIL";

export const DOWNVOTE = "DOWNVOTE";
export const DOWNVOTE_FAIL = "DOWNVOTE_FAIL";

export const CLEAR_VOTE_ERROR = "CLEAR_VOTE_ERROR";

// USER

export const FETCHING_USER = "FETCHING_USER";
export const FETCHING_USER_SUCCESS = "FETCHING_USER_SUCCESS";
export const FETCHING_USER_FAIL = "FETCHING_USER_FAIL";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const FETCHING_USER_POST = "FETCHING_USER_POST";
export const FETCHING_USER_POST_SUCCESS = "FETCHING_USER_POST_SUCCESS";
export const FETCHING_USER_POST_FAIL = "FETCHING_USER_POST_FAIL";

export const EDIT_POST = "EDIT_POST";
export const CANCEL_EDIT_POST = "CANCEL_EDIT_POST";
export const EDIT_POST_SUBMIT_SUCCESS = "EDIT_POST_SUBMIT_SUCCESS";

export const NEW_POST = "NEW_POST";
export const NEW_POST_SUBMIT_SUCCESS = "NEW_POST_SUBMIT_SUCCESS";
export const CANCEL_NEW_POST = "CANCEL_NEW_POST";

// COMMENT

export const FETCHING_COMMENT = "FETCH_COMMENT";
export const FETCHING_COMMENT_SUCCESS = "FETCH_COMMENT_SUCCESS";

export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
